development:
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 100
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_test
  pool: 5
  username: postgres
  password: root  
